apiVersion: apps/v1
kind: Deployment
metadata:
  name: question-service-app
spec:
  selector:
    matchLabels:
      app: question-service-app
  template:
    metadata:
      labels:
        app: question-service-app
    spec:
      containers:
      - name: question-service-app
        image: quizapp/question-service:0.0.1
        ports:
        - containerPort: 9041
        env:
          - name: EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE
            valueFrom:
              configMapKeyRef:
                key: eureka-service-address
                name: eureka-cm
          - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
            value: "true"
          - name: SPRING_DATASOURCE_URL
            value: jdbc:postgresql://pgsql-dev:5432/qustiondb
          - name: SPRING_DATASOURCE_USERNAME
            value: dev
          - name: SPRING_DATASOURCE_PASSWORD
            value: dev

---

apiVersion: v1
kind: Service
metadata:
  name: question-service-svc
spec:
  selector:
    app: question-service-app
  ports:
  - port: 80
    targetPort: 9041


